export const zinnen = {
    "base":{
        "nl":[
            "blinden kunnnen niet zien want _",
            "Apple onthuld de _ en mensen worden gek",
            "elon musk koopt _",
            "blinde mensen kunnen niet zien omdat _",
            "_ is verboden in China",
            "veel geld klinkt goed, maar _ klinkt beter",
            "_, is hoe ik dood wil",
            "er is een app voor _?",
            "_, dat is hoe maffia werkt",
            "ik zuip om _ te vergeten",
            "stap 1: _ Stap 2: Profiteer",
            "_ is mijn ergste nachtmerrie",
            "in het weekend _",
            "POV: _",
            "waarom staat _ niet in de grondwet?",
            "je bent gearresteerd vanwege _, Alweer!",
            "wij gaan zometeen Netflix en _",
            "deze app is net als Tinder, maar dan voor _",
            "_ zijn het grootste politieke probleem",
            "waarom staat _ in mijn zoekgeschiedenis?",
            "ik zou _ als Geert Wilders president zou worden",
            "rozen zijn rood, violen zijn blauw, _",
            "het is basaal _ maar dan voor nerds!",
            "_ is voor nerdddsss!",
            "_ was het waard",
            "5G is de oorzaak van _",
            "_ is nog een gefaald ict project van de overheid",
            "als ik een brein had om mee te denken, zou ik denken over _",
            "blijkbaar is _ illegaal",
            "ik blijf maagd tot _",
            "mijn jeugd is verpest door _",
            "eten, slapen en _",
            "achter elk programmeur zit _",
            "achter elk leerling zit _",
            "elke 60 seconde, _ in Africa",
            "ik ben altijd te laat voor _",
            "_ is hoe ik tijdelijk ontsnap aan de werkelijkheid",
            "als ik nu overal naartoe kon gaan, ging ik naar _",
            "ik wil proberen om _",
            "_ kwam het eerst",
            "_ is wat ik het beste vind aan de zomer",
            "ik ben helemaal klaar met _",
            "ik verdien een gouden medaille voor _",
            "ik kan niet zonder _",
            "ik erger me ontzettend aan _",
            "van mijn moeder moet ik _ na het eten",
            "deze kerst ben ik dankbaar voor _",
            "assistent! zet _ op de to-do lijst!",
            "waardoor zal ik nooit vergeten worden?",
            "_ is een nieuwe sociale media trend",
            "kijk, je weet dat ik van _, houd maar dat kan ik niet in het openbaar doen",
            "_ is niet de moeite waard",
            "wist je dat _ eigenlijk heel goed is voor je gezondheid?",
            "_ is het beste cadeau ooit!",
            "elke ochtend is het eerste dat ik doe _",
            "het enige erger dan in de friendzone zitten is _",
            "_ is beter dan het winnen van de loterij",
            "ik ga liever dood dan dat iemand weet van mijn passie voor _",
            "_ zou mij nooit zo erg laten schrikken als afgelopen nacht",
            "dit was de laatste keer dat ik _ probeerde",
            "ik kan drie weken zonder eten, drie dagen zonder drinken en drie minuten zonder _",
            "dus, wat gaan we doen dit weekend? _ zoals altijd?",
            "het volgende schilderij is een klassieker, het laat _ zien",
            "waarom wordt ik zo enthousiast van _",
            "mijn budget is zo klein, ik kan _ niet eens betalen",
            "een leuk, simpel en romantisch ding om te doen op Valentijnsdag is _",
            "goed, je bent een geweldadige alcoholist maar je bent in ieder geval geen _",
            "soms is _ de enige optie",
            "ik was erg verbaasd toen mijn moeder mij een nieuw artikel stuurde over _",
            "het geheim voor geluk is _",
            "_ is niet zo leuk als ze hadden beloofd",
            "weekend! Tijd voor _",
            "beste Kerstman, voor Kerst wil ik graag _",
            "_ had de Titanic kunnen redden",
            "ik zou nu liever _",
            "wat laat mijn vader lachen?",
            "_ is een heel goed idee, of een heel slecht idee",
            "als ik niet van _ had gehouden, hadden de terroristen gewonnen!",
            "_ bestaat niet echt, het is slechts een legende",
            "ik kan bevestigen dat _ meer pijn doet dan het stoten van je kleine teen",
            "_? Maak je geen zorgen Dat gebeurt constant hier in het Witte Huis",
            "_ kan leuk zijn voor jongens en meiden",
            "als _ slecht is, wil ik niet goed zijn",
            "volgens een studie, willen 69% van de mensen _ legaliseren",
            "blijkbaar is _ slecht voor je gezondheid",
            "vandaag gaan we allemaal _",
            "een waterstofbom bestaat uit water en _"
        ]
    }
}